Sprint 7 solution in file manager
aperanto-lefko/java-kanban pull request #4
Opened 2024-08-11 17:54 UTC by aperanto-lefko

Доработаны замечания по итогу 6 спринта, добавлены функции согласно ТЗ по 7 спринту

2024-08-12 19:17 UTC, sergeymamonov approved these changes
Проект становится все больше, поэтому нужно разложить классы по пакетам.

2024-08-12 19:17 UTC, sergeymamonov commented on src/FileBackedTaskManager.java
> +import java.io.*;
Не нужно использовать импорт через *.

2024-08-12 19:17 UTC, sergeymamonov commented on src/FileBackedTaskManager.java
> +            listOfActions.write(String.format("id,type,name,status,description,epic %n"));
Строку заголовков лучше вынести в константу с информативным названием.

2024-08-12 19:17 UTC, sergeymamonov commented on src/Main.java
> +        //FileBackedTaskManager taskManager = FileBackedTaskManager.loadFromFile(file);
Не оставляйте закомментированного кода в проекте.

2024-08-12 19:19 UTC, sergeymamonov requested changes

2024-08-12 19:19 UTC, sergeymamonov commented on src/InMemoryHistoryManager.java
> +                historyMap.remove(key);
Попробуйте упростить код. Сейчас он трудночитаемый. Например, эта строка повторяется в разных ветках. А значит его можно выделить из всех веток.

2024-08-13 11:22 UTC, aperanto-lefko commented on src/FileBackedTaskManager.java
> +import java.io.*;
Пробовала, но idea сама объединяет, когда несколько импортов io

2024-08-13 15:22 UTC, aperanto-lefko commented on src/FileBackedTaskManager.java
> +            listOfActions.write(String.format("id,type,name,status,description,epic %n"));
Добавила

2024-08-13 15:22 UTC, aperanto-lefko commented on src/InMemoryHistoryManager.java
> +                historyMap.remove(key);
Ничего не приходит в голову

2024-08-13 15:32 UTC, aperanto-lefko commented on src/InMemoryHistoryManager.java
> +                historyMap.remove(key);
к сожалению

2024-08-13 15:33 UTC, aperanto-lefko commented on src/Main.java
> +        //FileBackedTaskManager taskManager = FileBackedTaskManager.loadFromFile(file);
убрала

2024-08-13 19:56 UTC, sergeymamonov commented on src/FileBackedTaskManager.java
> +import java.io.*;
Гуглите. Это один из основных инструментов поиска решений.
Лучше отключить wildcard import https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcards-for-class

2024-08-13 20:12 UTC, sergeymamonov approved these changes

2024-08-13 20:12 UTC, sergeymamonov commented on src/managers/FileBackedTaskManager.java
> +    final String nameList = String.format("id,type,name,status,description,epic %n");
Лучше оформить как константу. 
И непонятно что такое %n? Процент - это оператор, в который что-то потом подставляется, n  вместе с обратным слешем дает перенос строки. Если хотели сделать перенос строки. То здесь и ниже нужно поправить на обратный слеш.

2024-08-14 06:59 UTC, merged